application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
- url: /admin.*
  script: admin.app

- url: /results/
  script: results.app

- url: /.* #Must be the last entry 
  script: vote.app

